[package]
name = "wort"
version = "0.3.0"
authors = ["Monte Johnston <johnston.monte@gmail.com>"]
description = "This is a command line utility to find the English translation of German Words."

[dependencies]
regex = "0.2"
time = "*"
getopts = "0.2"
